/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SaveDataV0 {
  state_version: "0";
  scenario_ref: {
    name: string;
    revision: string;
    checksum: string;
  };
  position: {
    label: string;
    index: number;
  };
  variables: {
    [k: string]: string | number | boolean | null;
  };
  read_history: string[];
  log: {
    seq: number;
    kind: string;
    payload: {
      [k: string]: unknown;
    };
  }[];
  choice_results: {
    at: string;
    choice_id: string;
    selected_index: number;
  }[];
  rng: {
    seed: string;
    step: number;
  };
}
