/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projects */
        get: operations["get_projects_api_v0_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v0_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/projects/{project_id}/scenario/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chapter Scenario */
        get: operations["get_chapter_scenario_api_v0_projects__project_id__scenario_chapters__chapter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/projects/{project_id}/saves/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Save */
        get: operations["get_save_api_v0_projects__project_id__saves__slot__get"];
        /** Put Save */
        put: operations["put_save_api_v0_projects__project_id__saves__slot__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChapterScenarioResponse */
        ChapterScenarioResponse: {
            /** Project Id */
            project_id: string;
            /** Chapter Id */
            chapter_id: string;
            scenario: components["schemas"]["ScenarioV0"];
            /** Warnings */
            warnings: string[];
        };
        /** ChoiceResult */
        ChoiceResult: {
            /** At */
            at: string;
            /** Choice Id */
            choice_id: string;
            /** Selected Index */
            selected_index: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogEntry */
        LogEntry: {
            /** Seq */
            seq: number;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** Position */
        Position: {
            /** Label */
            label: string;
            /** Index */
            index: number;
        };
        /** ProjectDetailResponse */
        ProjectDetailResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Entry Chapter */
            entry_chapter: string;
            /** Chapters */
            chapters: string[];
            /** Scenario Revision */
            scenario_revision: string;
            /** Assets Base Url */
            assets_base_url: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectSummary"][];
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Entry Chapter */
            entry_chapter: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RngState */
        RngState: {
            /** Seed */
            seed: string;
            /** Step */
            step: number;
        };
        /** SaveDataV0 */
        SaveDataV0: {
            /**
             * State Version
             * @constant
             */
            state_version: "0";
            scenario_ref: components["schemas"]["ScenarioRef"];
            position: components["schemas"]["Position"];
            /** Variables */
            variables: {
                [key: string]: string | number | boolean | null;
            };
            /** Read History */
            read_history?: string[];
            /** Log */
            log?: components["schemas"]["LogEntry"][];
            /** Choice Results */
            choice_results?: components["schemas"]["ChoiceResult"][];
            rng: components["schemas"]["RngState"];
        };
        /** SaveReadResponse */
        SaveReadResponse: {
            /** Project Id */
            project_id: string;
            /** Slot */
            slot: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            data: components["schemas"]["SaveDataV0"];
        };
        /** SaveWriteResponse */
        SaveWriteResponse: {
            /** Project Id */
            project_id: string;
            /** Slot */
            slot: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /** ScenarioRef */
        ScenarioRef: {
            /** Name */
            name: string;
            /** Revision */
            revision: string;
            /** Checksum */
            checksum: string;
        };
        /** ScenarioV0 */
        ScenarioV0: {
            /** Id */
            id: string;
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_projects_api_v0_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    get_project_api_v0_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_scenario_api_v0_projects__project_id__scenario_chapters__chapter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_save_api_v0_projects__project_id__saves__slot__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_save_api_v0_projects__project_id__saves__slot__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                slot: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDataV0"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
